Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'early_stopping_patience'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<ipython-input-84-2e22f6ebdfe6>", line 23, in train_model_sweep
    early_stopping_patience = config.early_stopping_patience  # 조기 종료 기준 에포크 수
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'early_stopping_patience'
